"use client";
import { useRouter } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import Footer from "../components/Footer";

export default function Tnc() {
    const router = useRouter();

    return (
        <div>
            <div className="max-w-4xl mx-auto px-4 py-8 font-fredoka mt-8">
                {/* Back Button */}
                <button
                    onClick={() => router.back()}
                    className="flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors mb-6 group"
                >
                    <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                    <span>Back</span>
                </button>

                <h1 className="text-3xl font-medium mb-6">Terms and Conditions</h1>

                <p className="mb-6 text-gray-600 font-normal">Effective Date: December 23, 2025</p>

                <p className="mb-6 font-normal">
                    Welcome to Kavisha.ai. By accessing or using our website and services, you agree to be bound by these Terms and Conditions. Please read them carefully.
                </p>

                <section className="mb-6">
                    <h2 className="text-2xl font-medium mb-3">1. Description of Service</h2>
                    <p className="font-normal">
                        Kavisha.ai provides a platform that utilizes Artificial Intelligence to create digital avatars of influential individuals, allowing users to engage in simulated conversations. Our service is designed to facilitate human connections, whether for recruitment, career advancement, or social networking.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-medium mb-3">2. Nature of AI Interactions</h2>
                    <p className="mb-2 font-normal">Simulated Content: You acknowledge that the digital avatars are AI-driven simulations. While they are modeled after influential people, the responses are generated by algorithms and do not constitute direct, real-time communication with the physical individual.</p>
                    <p className="mb-2 font-normal">No Professional Advice: Conversations with Kavisha or any digital avatar are for informational and networking purposes only. They do not constitute professional, legal, medical or financial advice.</p>
                    <p className="font-normal">AI Limitations: AI can occasionally produce inaccurate or biased information. Kavisha.ai is not responsible for any "hallucinations" or inaccuracies generated by the AI.</p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-medium mb-3">3. User Accounts and Eligibility</h2>
                    <p className="mb-2 font-normal">Age Requirement: You must be at least 18 years old (or the age of majority in your jurisdiction) to use this service.</p>
                    <p className="font-normal">Account Accuracy: You agree to provide truthful information when setting up your profile to ensure the "perfect match" functionality works effectively for recruitment or networking.</p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-medium mb-3">4. Intellectual Property</h2>
                    <p className="mb-2 font-normal">Ownership: Kavisha.ai and its licensors own all rights, titles, and interests in the AI models, software, website design, and the digital avatars.</p>
                    <p className="font-normal">Limited License: We grant you a personal, non-exclusive, non-transferable license to interact with the avatars for your own personal or professional use. You may not scrape, reverse-engineer, or attempt to extract the underlying code or data of our AI models.</p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-medium mb-3">5. Data Usage and Privacy</h2>
                    <p className="mb-2 font-normal">Your privacy is central to our mission of "Human Connection."</p>
                    <p className="mb-2 font-normal">Conversation Data: By talking to Kavisha, you grant us permission to analyze your conversations to improve our matching algorithm and help find the "perfect" person for your needs (e.g., matching a recruiter with a candidate).</p>
                    <p className="font-normal">Privacy Policy: All data handling is governed by our Privacy Policy.</p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-medium mb-3">6. User Conduct</h2>
                    <p className="mb-2 font-normal">To maintain a safe environment, you agree not to:</p>
                    <ul className="list-disc list-inside mb-2 space-y-1 font-normal">
                        <li>Use the service to harass, abuse, or threaten others.</li>
                        <li>Input sensitive personal data (e.g., social security numbers, passwords) into the chat.</li>
                        <li>Attempt to "jailbreak" or manipulate the AI into generating harmful or prohibited content.</li>
                    </ul>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-3">7. Limitation of Liability</h2>
                    <p>
                        Kavisha.ai shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to employment decisions made based on AI interactions or the failure to find a "perfect" match.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-medium mb-3">8. Termination</h2>
                    <p className="font-normal">
                        We reserve the right to suspend or terminate your access to Kavisha.ai at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users or the platform.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-3">9. Governing Law</h2>
                    <p>
                        These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Kavisha.ai (Contrarian Technologies pvt. ltd.) is registered, without regard to its conflict of law provisions.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-medium mb-3">10. Changes to Terms</h2>
                    <p className="font-normal">
                        We may update these Terms from time to time. Your continued use of the platform after changes are posted constitutes your acceptance of the new Terms.
                    </p>
                </section>

                <section className="mb-6">
                    <h2 className="text-2xl font-semibold mb-3">Contact Us</h2>
                    <p>
                        If you have any questions regarding these Terms, please contact us at: <a href="mailto:hello@kavisha.ai" className="text-blue-600 hover:underline">hello@kavisha.ai</a>
                    </p>
                </section>
            </div>

            <Footer />
        </div>
    );
}