name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # deploys when code is merged to main
  workflow_dispatch: # allow manual trigger

env:
  PROJECT_ID: kavisha-ai-468913
  REGION: us-central1
  SERVICE: kavisha-ai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker auth
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          IMAGE=gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push Docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update ${{ env.SERVICE }} \
            --image $IMAGE \
            --region ${{ env.REGION }} \
            --platform managed
